### ISSUE TITLE
Whoops

### ISSUE THREAD

**Issue by 13Clowns** [jewbmx/JewBackD#1]
Hey I've been meaning to get this to you. I pulled a few scrapers from you and I forgot to pull them before I pushed an update to Lambda. 

I was trying some things out and they got left behind. 

I'll pull them out if you like.

Clown man.

**Comment by 13Clowns** [comment]
going to close as I havent heard back!

**Comment by jewbmx** [comment]
My bad didnt see your post lol, i look in my normal repo for issues and didnt think to check this repo.

**Comment by 13Clowns** [comment]
Thanks for getting back.
